//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kirill.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kirill.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wheel {
            get {
                object obj = ResourceManager.GetObject("wheel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на River | A flowing body of water.
        ///Mountain | A large elevated landform rising significantly above its surroundings.
        ///Forest | A large area covered chiefly with trees and undergrowth.
        ///Lake | A large body of water surrounded by land.
        ///Desert | A dry, barren area of land, often covered with sand.
        ///Sun | The star at the center of our solar system that provides light and heat.
        ///Moon | Earth&apos;s natural satellite that orbits the planet.
        ///Star | A luminous celestial body made of gas.
        ///Planet | A celestial body orbi [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string wordsEN {
            get {
                return ResourceManager.GetString("wordsEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Река|Вода течет в этом объекте.
        ///Гора|Высокий возвышенный участок земной коры.
        ///Лес|Большая площадь земли, покрытая деревьями.
        ///Озеро|Водоем, меньший по размеру, чем море.
        ///Пустыня|Сухая, обширная территория.
        ///Солнце|Звезда, вокруг которой вращается Земля.
        ///Луна|Естественный спутник Земли.
        ///Звезда|Светящееся небесное тело, состоящее из газа.
        ///Планета|Космическое тело, вращающееся вокруг звезды.
        ///Галактика|Массированная система звезд, газа и пыли.
        ///Комета|Космическое тело с хвостом, состоящее из льда и пыли. [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string wordsRU {
            get {
                return ResourceManager.GetString("wordsRU", resourceCulture);
            }
        }
    }
}
